"""
Analyzer V2 - Improved version with detailed charts and an HTML dashboard
"""
import os
import json
import pandas as pd
import numpy as np
from datetime import datetime


def _compute_streak_lengths(series: pd.Series, target_value: int) -> list:
    """Return contiguous streak lengths where series == target_value."""
    streaks = []
    current = 0
    for value in series.fillna(target_value):
        if int(value) == target_value:
            current += 1
        else:
            if current > 0:
                streaks.append(current)
                current = 0
    if current > 0:
        streaks.append(current)
    return streaks


def analyze_actions_v2(actions_csv: str = "backtest/data/xauusd_actions.csv",
                       initial_capital: float = 10000.0,
                       save_dir: str = "backtest/plots"):
    """
    Analyzes actions and trades and generates detailed charts + an HTML dashboard
    """
    os.makedirs(save_dir, exist_ok=True)

    if not os.path.exists(actions_csv):
        raise FileNotFoundError(f"Actions CSV not found: {actions_csv}")

    df = pd.read_csv(actions_csv)

    # Ensure Time is datetime and prices are numeric
    if "Time" in df.columns:
        df["Time"] = pd.to_datetime(df["Time"])
    for col in ["Open", "High", "Low", "Close"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    exported_equity = None
    if "Equity" in df.columns:
        exported_equity = pd.to_numeric(df["Equity"], errors="coerce")

    # ================================================================
    # ACTION ANALYSIS
    # ================================================================
    action_names = {0: "HOLD", 1: "LONG", 2: "SHORT", 3: "CLOSE"}
    df["Action"] = pd.to_numeric(df["Action"], errors="coerce").fillna(0).astype(int)
    action_counts = df["Action"].value_counts().to_dict()
    total_steps = len(df)
    active_steps = int((df["Action"] != 0).sum())
    active_steps_pct = 100.0 * active_steps / total_steps if total_steps > 0 else 0.0

    hold_streaks = _compute_streak_lengths(df["Action"], 0)
    max_hold_streak = int(max(hold_streaks)) if hold_streaks else 0
    avg_hold_streak = float(np.mean(hold_streaks)) if hold_streaks else 0.0

    print("\n" + "="*70)
    print("ACTIONS GENERATED BY THE RL MODEL")
    print("="*70)
    denom_steps = max(total_steps, 1)
    for action_id in [0, 1, 2, 3]:
        count = action_counts.get(action_id, 0)
        pct = 100.0 * count / denom_steps
        print(f"  {action_names[action_id]:6s}: {count:5d} ({pct:5.1f}%)")
    print(f"  ACTIVE: {active_steps:5d} ({active_steps_pct:5.1f}%)")
    print(f"  HOLD streak max: {max_hold_streak} step")

    # ================================================================
    # TRADE SIMULATION
    # ================================================================
    position = 0
    entry_price = None
    capital = initial_capital
    trade_results = []
    per_step_equity = []
    per_step_position = []
    per_step_entry_price = []

    for idx, row in df.iterrows():
        action = int(row.get("Action", 0))
        price = float(row.get("Close", np.nan))

        realized_pnl = 0.0
        trade_type = None

        if np.isnan(price):
            per_step_equity.append(capital)
            per_step_position.append(position)
            per_step_entry_price.append(entry_price)
            continue

        # Action handling
        if action == 1:  # LONG
            if position <= 0:
                if position == -1 and entry_price is not None:
                    realized_pnl = (entry_price - price) / entry_price
                    trade_type = "cover_short"
                    trade_results.append({
                        "type": trade_type, "pnl": realized_pnl,
                        "close_idx": idx, "close_price": price
                    })
                position = 1
                entry_price = price

        elif action == 2:  # SHORT
            if position >= 0:
                if position == 1 and entry_price is not None:
                    realized_pnl = (price - entry_price) / entry_price
                    trade_type = "close_long"
                    trade_results.append({
                        "type": trade_type, "pnl": realized_pnl,
                        "close_idx": idx, "close_price": price
                    })
                position = -1
                entry_price = price

        elif action == 3:  # CLOSE
            if position == 1 and entry_price is not None:
                realized_pnl = (price - entry_price) / entry_price
                trade_type = "close_long"
                trade_results.append({
                    "type": trade_type, "pnl": realized_pnl,
                    "close_idx": idx, "close_price": price
                })
            elif position == -1 and entry_price is not None:
                realized_pnl = (entry_price - price) / entry_price
                trade_type = "cover_short"
                trade_results.append({
                    "type": trade_type, "pnl": realized_pnl,
                    "close_idx": idx, "close_price": price
                })
            position = 0
            entry_price = None

        capital += realized_pnl * capital
        per_step_equity.append(capital)
        per_step_position.append(position)
        per_step_entry_price.append(entry_price)

    # If position still open at the end, close it at last price
    if position != 0 and entry_price is not None:
        try:
            last_price = float(df.iloc[-1].get("Close", np.nan))
            if not np.isnan(last_price):
                if position == 1:
                    realized_pnl = (last_price - entry_price) / entry_price
                    trade_results.append({
                        "type": "close_long", "pnl": realized_pnl,
                        "close_idx": len(df) - 1, "close_price": last_price
                    })
                elif position == -1:
                    realized_pnl = (entry_price - last_price) / entry_price
                    trade_results.append({
                        "type": "cover_short", "pnl": realized_pnl,
                        "close_idx": len(df) - 1, "close_price": last_price
                    })
                # update equity arrays to reflect final close
                capital += realized_pnl * capital
                per_step_equity[-1] = capital
        except Exception:
            pass

    equity_source = "reconstructed"
    if exported_equity is not None and len(exported_equity) == len(df):
        exported_valid_ratio = float(exported_equity.notna().mean()) if len(df) > 0 else 0.0
        if exported_valid_ratio >= 0.95:
            df["Equity"] = exported_equity.ffill().bfill()
            equity_source = "exported"
        else:
            df["Equity"] = per_step_equity
    else:
        df["Equity"] = per_step_equity
    df["Position"] = per_step_position

    # ================================================================
    # STATISTICS
    # ================================================================
    trades_df = pd.DataFrame(trade_results)
    total_trades = len(trades_df)
    profitable_trades = trades_df[trades_df["pnl"] > 0].shape[0] if total_trades > 0 else 0
    pct_profitable = 100.0 * profitable_trades / total_trades if total_trades > 0 else 0.0
    final_capital = float(df["Equity"].iloc[-1]) if len(df) > 0 else float(initial_capital)
    total_return_pct = 100.0 * (final_capital - initial_capital) / initial_capital
    max_equity = float(df["Equity"].max()) if len(df) > 0 else float(initial_capital)
    min_equity = float(df["Equity"].min()) if len(df) > 0 else float(initial_capital)
    equity_arr = pd.to_numeric(df["Equity"], errors="coerce").ffill().bfill().to_numpy(dtype=float) if len(df) > 0 else np.array([], dtype=float)
    if equity_arr.size > 0:
        running_max = np.maximum.accumulate(equity_arr)
        drawdown_pct = (equity_arr - running_max) / (running_max + 1e-9) * 100.0
        max_drawdown_pct = float(np.min(drawdown_pct))
    else:
        max_drawdown_pct = 0.0

    per_type = trades_df.groupby("type")["pnl"].agg(["count", "sum", "mean"]).to_dict() if total_trades > 0 else {}

    forced_action_count = 0
    hard_stop_count = 0
    if "ForcedAction" in df.columns:
        forced_action_count = int(df["ForcedAction"].astype(str).str.lower().isin(["true", "1"]).sum())
    if "HardStop" in df.columns:
        hard_stop_count = int(df["HardStop"].astype(str).str.lower().isin(["true", "1"]).sum())

    time_coverage = {}
    monthly_activity = []
    if "Time" in df.columns and total_steps > 0:
        day_series = df["Time"].dt.date
        total_days = int(day_series.nunique())
        active_days = int(day_series[df["Action"] != 0].nunique())
        time_coverage = {
            "total_days": total_days,
            "active_days": active_days,
            "active_days_pct": (100.0 * active_days / total_days) if total_days > 0 else 0.0,
        }

        month_df = df.copy()
        month_df["YearMonth"] = month_df["Time"].dt.to_period("M").astype(str)
        month_df["Active"] = (month_df["Action"] != 0).astype(int)
        month_stats = month_df.groupby("YearMonth")["Active"].sum().reset_index()
        monthly_activity = [
            {"period": row["YearMonth"], "active_steps": int(row["Active"])}
            for _, row in month_stats.iterrows()
        ]

    regime_action_distribution = {}
    if "Regime" in df.columns:
        regime_vals = pd.to_numeric(df["Regime"], errors="coerce").fillna(-1).astype(int)
        regime_counts = (
            pd.DataFrame({"Regime": regime_vals, "Action": df["Action"]})
            .groupby(["Regime", "Action"])
            .size()
            .unstack(fill_value=0)
        )
        for regime_id, row in regime_counts.iterrows():
            regime_action_distribution[str(int(regime_id))] = {
                action_names.get(int(action_id), str(action_id)): int(row.get(action_id, 0))
                for action_id in [0, 1, 2, 3]
            }

    danger_action_distribution = {}
    danger_position_size = {}
    if "DangerLevel" in df.columns:
        danger_vals = pd.to_numeric(df["DangerLevel"], errors="coerce").fillna(0).astype(int)
        danger_counts = (
            pd.DataFrame({"DangerLevel": danger_vals, "Action": df["Action"]})
            .groupby(["DangerLevel", "Action"])
            .size()
            .unstack(fill_value=0)
        )
        for danger_id, row in danger_counts.iterrows():
            danger_action_distribution[str(int(danger_id))] = {
                action_names.get(int(action_id), str(action_id)): int(row.get(action_id, 0))
                for action_id in [0, 1, 2, 3]
            }
        if "PositionSize" in df.columns:
            pos_series = pd.to_numeric(df["PositionSize"], errors="coerce")
            pos_by_danger = pd.DataFrame({"DangerLevel": danger_vals, "PositionSize": pos_series}).groupby("DangerLevel")["PositionSize"].mean()
            danger_position_size = {str(int(k)): float(v) for k, v in pos_by_danger.items()}

    bias_flags = []
    hold_pct = 100.0 * action_counts.get(0, 0) / total_steps if total_steps > 0 else 0.0
    long_count = action_counts.get(1, 0)
    short_count = action_counts.get(2, 0)
    if hold_pct >= 95.0:
        bias_flags.append("excessive_hold_behavior")
    if long_count == 0 or short_count == 0:
        bias_flags.append("directional_imbalance_long_or_short_missing")
    elif (long_count + short_count) > 0:
        minority_ratio = min(long_count, short_count) / (long_count + short_count)
        if minority_ratio < 0.05:
            bias_flags.append("directional_imbalance_extreme")
    if total_trades < 5 and total_steps > 1000:
        bias_flags.append("too_few_closed_trades_for_reliable_signal")
    if max_hold_streak > max(500, int(total_steps * 0.05)):
        bias_flags.append("very_long_hold_streak")

    stats = {
        "initial_capital": initial_capital,
        "final_capital": final_capital,
        "total_return_pct": total_return_pct,
        "total_trades": total_trades,
        "profitable_trades": profitable_trades,
        "pct_profitable": pct_profitable,
        "max_equity": max_equity,
        "min_equity": min_equity,
        "max_drawdown_pct": max_drawdown_pct,
        "per_type": per_type,
        "steps": total_steps,
        "active_steps": active_steps,
        "active_steps_pct": active_steps_pct,
        "no_action_steps": int((df["Action"] == 0).sum()),
        "max_hold_streak": max_hold_streak,
        "avg_hold_streak": avg_hold_streak,
        "forced_action_count": forced_action_count,
        "hard_stop_count": hard_stop_count,
        "time_coverage": time_coverage,
        "monthly_activity": monthly_activity,
        "regime_action_distribution": regime_action_distribution,
        "danger_action_distribution": danger_action_distribution,
        "danger_position_size_mean": danger_position_size,
        "equity_source": equity_source,
        "bias_flags": bias_flags,
        "action_distribution": {
            "HOLD": int(action_counts.get(0, 0)),
            "LONG": int(action_counts.get(1, 0)),
            "SHORT": int(action_counts.get(2, 0)),
            "CLOSE": int(action_counts.get(3, 0)),
        }
    }

    print("\n" + "="*70)
    print("TRADING RESULTS")
    print("="*70)
    print(f"  Starting capital:  ${initial_capital:,.2f}")
    print(f"  Final capital:     ${final_capital:,.2f} ({equity_source})")
    print(f"  Total return:      {total_return_pct:+.2f}%")
    print(f"  Total trades:      {total_trades}")
    print(f"  Profitable:        {profitable_trades} ({pct_profitable:.1f}%)")
    print(f"  Max equity:        ${max_equity:,.2f}")
    print(f"  Max drawdown:      {max_drawdown_pct:.2f}%")
    print(f"  Active steps:      {active_steps} ({active_steps_pct:.1f}%)")
    print(f"  HOLD streak max:   {max_hold_streak} step")
    if bias_flags:
        print(f"  Bias flags:        {', '.join(bias_flags)}")
    else:
        print("  Bias flags:        none")

    # ================================================================
    # CHARTS
    # ================================================================
    try:
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches
        from matplotlib.dates import DateFormatter
        import matplotlib.dates as mdates

        # 1. Equity curve with buy/sell actions overlay
        fig, ax = plt.subplots(figsize=(16, 6))
        ax.plot(df["Time"], df["Equity"], linewidth=2, label="Equity", color="black")
        ax.axhline(y=initial_capital, color="gray", linestyle="--", alpha=0.5, label="Initial Capital")
        ax.fill_between(df["Time"], initial_capital, df["Equity"],
                        where=(df["Equity"] >= initial_capital),
                        alpha=0.2, color="green", label="Profit")
        ax.fill_between(df["Time"], initial_capital, df["Equity"],
                        where=(df["Equity"] < initial_capital),
                        alpha=0.2, color="red", label="Loss")

        # Overlay trades
        if total_trades > 0:
            for _, trade in trades_df.iterrows():
                idx = int(trade["close_idx"])
                if idx < len(df):
                    color = "green" if trade["pnl"] > 0 else "red"
                    time_val = df.iloc[idx]["Time"]
                    equity_val = df.iloc[idx]["Equity"]
                    marker = "o" if trade["pnl"] > 0 else "x"
                    ax.plot(time_val, equity_val, marker, markersize=8, color=color, alpha=0.7)

        ax.set_xlabel("Time", fontsize=12)
        ax.set_ylabel("Equity ($)", fontsize=12)
        ax.set_title("Equity Curve with Trade Markers (Green=Profit, Red=Loss)", fontsize=14, fontweight="bold")
        ax.legend(loc="upper left")
        ax.grid(True, alpha=0.3)
        ax.xaxis.set_major_formatter(DateFormatter("%Y-%m-%d"))
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, "01_equity_curve_trades.png"), dpi=100)
        plt.close()
        print("  [OK] Saved: 01_equity_curve_trades.png")

        # 2. Action distribution
        fig, ax = plt.subplots(figsize=(8, 5))
        actions = [action_names[i] for i in [0, 1, 2, 3]]
        counts = [action_counts.get(i, 0) for i in [0, 1, 2, 3]]
        colors = ["gray", "green", "red", "orange"]
        ax.bar(actions, counts, color=colors, alpha=0.7, edgecolor="black")
        ax.set_ylabel("Count", fontsize=11)
        ax.set_title("Action Distribution", fontsize=12, fontweight="bold")
        ax.grid(axis="y", alpha=0.3)
        for i, v in enumerate(counts):
            ax.text(i, v + max(counts)*0.01, str(v), ha="center", fontweight="bold")
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, "02_action_distribution.png"), dpi=100)
        plt.close()
        print("  [OK] Saved: 02_action_distribution.png")

        # 3. PnL per trade type (bar chart)
        if total_trades > 0 and not trades_df.empty:
            fig, ax = plt.subplots(figsize=(8, 5))
            trade_types = trades_df["type"].value_counts()
            colors_map = {"close_long": "blue", "cover_short": "orange"}
            colors = [colors_map.get(t, "gray") for t in trade_types.index]
            ax.bar(range(len(trade_types)), trade_types.values, color=colors, alpha=0.7, edgecolor="black")
            ax.set_xticks(range(len(trade_types)))
            ax.set_xticklabels(trade_types.index, rotation=0)
            ax.set_ylabel("Count", fontsize=11)
            ax.set_title("Trade Count by Type", fontsize=12, fontweight="bold")
            ax.grid(axis="y", alpha=0.3)
            for i, v in enumerate(trade_types.values):
                ax.text(i, v + 0.5, str(v), ha="center", fontweight="bold")
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, "03_pnl_per_type.png"), dpi=100)
            plt.close()
            print("  [OK] Saved: 03_pnl_per_type.png")

            # 4. Per-trade PnL histogram
            fig, ax = plt.subplots(figsize=(8, 5))
            pnls = trades_df["pnl"].dropna()
            ax.hist(pnls, bins=40, color="skyblue", edgecolor="black", alpha=0.7)
            ax.axvline(pnls.mean(), color="red", linestyle="--", linewidth=2, label=f"Mean: {pnls.mean():.4f}")
            ax.set_xlabel("PnL (fraction)", fontsize=11)
            ax.set_ylabel("Trades", fontsize=11)
            ax.set_title(f"Per-Trade PnL Distribution (n={len(pnls)})", fontsize=12, fontweight="bold")
            ax.legend()
            ax.grid(axis="y", alpha=0.3)
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, "04_trade_pnl_histogram.png"), dpi=100)
            plt.close()
            print("  [OK] Saved: 04_trade_pnl_histogram.png")

        # 5. Position over time
        fig, ax = plt.subplots(figsize=(14, 4))
        ax.plot(df["Time"], df["Position"], linewidth=1.5, color="purple", alpha=0.7)
        ax.fill_between(df["Time"], 0, df["Position"], where=(df["Position"] > 0),
                       alpha=0.3, color="green", label="LONG")
        ax.fill_between(df["Time"], 0, df["Position"], where=(df["Position"] < 0),
                       alpha=0.3, color="red", label="SHORT")
        ax.set_ylabel("Position", fontsize=11)
        ax.set_title("Position over Time (1=LONG, 0=NONE, -1=SHORT)", fontsize=12, fontweight="bold")
        ax.set_ylim([-1.5, 1.5])
        ax.legend()
        ax.grid(True, alpha=0.3)
        ax.xaxis.set_major_formatter(DateFormatter("%Y-%m-%d"))
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, "05_position_over_time.png"), dpi=100)
        plt.close()
        print("  [OK] Saved: 05_position_over_time.png")

        # 6. Monthly activity (non-HOLD actions per month)
        if monthly_activity:
            month_df = pd.DataFrame(monthly_activity)
            fig, ax = plt.subplots(figsize=(14, 4))
            ax.bar(month_df["period"], month_df["active_steps"], color="#2a9d8f", alpha=0.8, edgecolor="black")
            ax.set_title("Monthly Active Steps (non-HOLD actions)", fontsize=12, fontweight="bold")
            ax.set_ylabel("Active Steps", fontsize=11)
            ax.grid(axis="y", alpha=0.3)
            # Downsample xticks for readability
            if len(month_df) > 24:
                step_ticks = max(1, len(month_df) // 12)
                ax.set_xticks(range(0, len(month_df), step_ticks))
                ax.set_xticklabels(month_df["period"].iloc[::step_ticks], rotation=45, ha="right")
            else:
                ax.set_xticks(range(len(month_df)))
                ax.set_xticklabels(month_df["period"], rotation=45, ha="right")
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, "06_activity_by_month.png"), dpi=100)
            plt.close()
            print("  [OK] Saved: 06_activity_by_month.png")

        # 7. Action distribution by regime
        if regime_action_distribution:
            regime_plot_df = pd.DataFrame(regime_action_distribution).T
            for col in ["HOLD", "LONG", "SHORT", "CLOSE"]:
                if col not in regime_plot_df.columns:
                    regime_plot_df[col] = 0
            regime_plot_df = regime_plot_df[["HOLD", "LONG", "SHORT", "CLOSE"]]
            regime_plot_df = regime_plot_df.sort_index()

            fig, ax = plt.subplots(figsize=(10, 5))
            bottom = np.zeros(len(regime_plot_df))
            colors = {"HOLD": "gray", "LONG": "green", "SHORT": "red", "CLOSE": "orange"}
            for col in ["HOLD", "LONG", "SHORT", "CLOSE"]:
                values = regime_plot_df[col].astype(float).values
                ax.bar(regime_plot_df.index, values, bottom=bottom, label=col, color=colors[col], alpha=0.85)
                bottom += values
            ax.set_title("Action Distribution by Regime", fontsize=12, fontweight="bold")
            ax.set_xlabel("Regime", fontsize=11)
            ax.set_ylabel("Count", fontsize=11)
            ax.legend()
            ax.grid(axis="y", alpha=0.3)
            plt.tight_layout()
            plt.savefig(os.path.join(save_dir, "07_action_by_regime.png"), dpi=100)
            plt.close()
            print("  [OK] Saved: 07_action_by_regime.png")

    except Exception as e:
        print(f"  [ERR] Plotting failed: {e}")

    # ================================================================
    # SAVE JSON SUMMARY
    # ================================================================
    with open(os.path.join(save_dir, "analysis_summary.json"), "w") as f:
        json.dump(stats, f, indent=2)

    # ================================================================
    # GENERATE HTML DASHBOARD
    # ================================================================
    extra_charts_html = ""
    if os.path.exists(os.path.join(save_dir, "06_activity_by_month.png")):
        extra_charts_html += '<div class="chart"><img src="06_activity_by_month.png" alt="Monthly Activity"></div>'
    if os.path.exists(os.path.join(save_dir, "07_action_by_regime.png")):
        extra_charts_html += '<div class="chart"><img src="07_action_by_regime.png" alt="Action by Regime"></div>'

    bias_flags_text = ", ".join(bias_flags) if bias_flags else "none"

    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RL Trading Analysis Dashboard</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
            padding: 20px;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            padding: 30px;
        }}
        h1 {{
            color: #667eea;
            margin-bottom: 30px;
            text-align: center;
            font-size: 2.5em;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 40px;
        }}
        .stat-card {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        }}
        .stat-card h3 {{
            font-size: 0.9em;
            font-weight: normal;
            opacity: 0.9;
            margin-bottom: 10px;
        }}
        .stat-card .value {{
            font-size: 1.8em;
            font-weight: bold;
        }}
        .stat-card.positive {{
            background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
        }}
        .stat-card.negative {{
            background: linear-gradient(135deg, #ee0979 0%, #ff6a00 100%);
        }}
        .stat-card.neutral {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }}
        .charts-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 20px;
            margin-bottom: 40px;
        }}
        .chart {{
            border: 2px solid #e0e0e0;
            border-radius: 8px;
            padding: 15px;
            background: #fafafa;
        }}
        .chart img {{
            width: 100%;
            height: auto;
            border-radius: 5px;
        }}
        .details {{
            background: #f5f5f5;
            padding: 20px;
            border-radius: 8px;
            margin-top: 30px;
        }}
        .details h2 {{
            color: #667eea;
            margin-bottom: 15px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #667eea;
            color: white;
        }}
        tr:hover {{
            background: #f9f9f9;
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            color: #999;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 RL Trading Analysis Dashboard</h1>

        <div class="stats-grid">
            <div class="stat-card {'positive' if total_return_pct >= 0 else 'negative'}">
                <h3>Total Return</h3>
                <div class="value">{total_return_pct:+.2f}%</div>
            </div>
            <div class="stat-card neutral">
                <h3>Final Capital</h3>
                <div class="value">${final_capital:,.0f}</div>
            </div>
            <div class="stat-card neutral">
                <h3>Total Trades</h3>
                <div class="value">{total_trades}</div>
            </div>
            <div class="stat-card {'positive' if pct_profitable >= 50 else 'negative'}">
                <h3>Win Rate</h3>
                <div class="value">{pct_profitable:.1f}%</div>
            </div>
            <div class="stat-card negative">
                <h3>Max Drawdown</h3>
                <div class="value">{max_drawdown_pct:.2f}%</div>
            </div>
            <div class="stat-card neutral">
                <h3>Profitable Trades</h3>
                <div class="value">{profitable_trades}/{total_trades}</div>
            </div>
            <div class="stat-card neutral">
                <h3>Active Steps</h3>
                <div class="value">{active_steps_pct:.1f}%</div>
            </div>
            <div class="stat-card neutral">
                <h3>Max HOLD Streak</h3>
                <div class="value">{max_hold_streak}</div>
            </div>
        </div>

        <div class="charts-grid">
            <div class="chart">
                <img src="01_equity_curve_trades.png" alt="Equity Curve with Trades">
            </div>
            <div class="chart">
                <img src="02_action_distribution.png" alt="Action Distribution">
            </div>
            <div class="chart">
                <img src="05_position_over_time.png" alt="Position Over Time">
            </div>
            {'<div class="chart"><img src="03_pnl_per_type.png" alt="PnL per Type"></div>' if total_trades > 0 else ''}
            {'<div class="chart"><img src="04_trade_pnl_histogram.png" alt="Trade PnL Histogram"></div>' if total_trades > 0 else ''}
            {extra_charts_html}
        </div>

        <div class="details">
            <h2>📈 Performance Metrics</h2>
            <table>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td>Initial Capital</td>
                    <td>${initial_capital:,.2f}</td>
                </tr>
                <tr>
                    <td>Final Capital</td>
                    <td>${final_capital:,.2f}</td>
                </tr>
                <tr>
                    <td>Total Return</td>
                    <td>{total_return_pct:+.2f}%</td>
                </tr>
                <tr>
                    <td>Total Steps</td>
                    <td>{total_steps}</td>
                </tr>
                <tr>
                    <td>Active Steps</td>
                    <td>{active_steps} ({active_steps_pct:.1f}%)</td>
                </tr>
                <tr>
                    <td>Total Trades Closed</td>
                    <td>{total_trades}</td>
                </tr>
                <tr>
                    <td>Profitable Trades</td>
                    <td>{profitable_trades} ({pct_profitable:.1f}%)</td>
                </tr>
                <tr>
                    <td>Max Equity</td>
                    <td>${max_equity:,.2f}</td>
                </tr>
                <tr>
                    <td>Min Equity</td>
                    <td>${min_equity:,.2f}</td>
                </tr>
                <tr>
                    <td>Max Drawdown</td>
                    <td>{max_drawdown_pct:.2f}%</td>
                </tr>
                <tr>
                    <td>Max HOLD Streak</td>
                    <td>{max_hold_streak}</td>
                </tr>
                <tr>
                    <td>Bias Flags</td>
                    <td>{bias_flags_text}</td>
                </tr>
            </table>

            <h2>🎯 Action Distribution</h2>
            <table>
                <tr>
                    <th>Action</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
                <tr>
                    <td>HOLD (0)</td>
                    <td>{stats['action_distribution']['HOLD']}</td>
                    <td>{100*stats['action_distribution']['HOLD']/total_steps:.1f}%</td>
                </tr>
                <tr>
                    <td>LONG (1)</td>
                    <td>{stats['action_distribution']['LONG']}</td>
                    <td>{100*stats['action_distribution']['LONG']/total_steps:.1f}%</td>
                </tr>
                <tr>
                    <td>SHORT (2)</td>
                    <td>{stats['action_distribution']['SHORT']}</td>
                    <td>{100*stats['action_distribution']['SHORT']/total_steps:.1f}%</td>
                </tr>
                <tr>
                    <td>CLOSE (3)</td>
                    <td>{stats['action_distribution']['CLOSE']}</td>
                    <td>{100*stats['action_distribution']['CLOSE']/total_steps:.1f}%</td>
                </tr>
            </table>
        </div>

        <div class="footer">
            Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | RL Trading System
        </div>
    </div>
</body>
</html>
"""

    html_path = os.path.join(save_dir, "dashboard.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print("  [OK] Saved: dashboard.html")

    print("\n" + "="*70)
    print(f"Analysis complete! Open: {os.path.abspath(html_path)}")
    print("="*70 + "\n")

    return stats


if __name__ == "__main__":
    try:
        stats = analyze_actions_v2()
    except Exception as e:
        print(f"Analysis failed: {e}")
        import traceback
        traceback.print_exc()
