import backtrader as bt
import pandas as pd


class RLActionStrategy(bt.Strategy):
    """
    Backtrader strategy that executes ONLY the actions generated by the RL agent.
    The actions are:
        0 = Hold
        1 = Long
        2 = Short
        3 = Close
    """

    params = dict(
        actions_df=None,     # DataFrame with Time + Action
        sl_atr=1.0,          # Stop Loss = ATR * sl_atr
        tp_atr=2.0           # Take Profit = ATR * tp_atr
    )

    def __init__(self):
        # Convert the DF into a {timestamp: action} dictionary
        self.action_map = {
            pd.to_datetime(row["Time"]): int(row["Action"])
            for _, row in self.p.actions_df.iterrows()
        }

        # ATR for dynamic SL/TP
        self.atr = bt.indicators.ATR(self.data, period=14)

        self.order = None

    def next(self):
        dt = pd.to_datetime(self.data.datetime.datetime())

        if dt not in self.action_map:
            return

        action = self.action_map[dt]

        # If an order is pending → wait
        if self.order:
            return

        # Close the position
        if action == 3:
            if self.position:
                self.close()
            return

        # LONG
        if action == 1:
            if self.position.size <= 0:
                if self.position.size < 0:
                    self.close()
                self.buy()
                self._apply_sl_tp()

        # SHORT
        elif action == 2:
            if self.position.size >= 0:
                if self.position.size > 0:
                    self.close()
                self.sell()
                self._apply_sl_tp()

        # HOLD → do nothing
        else:
            pass

    def _apply_sl_tp(self):
        """
        Applies dynamic SL/TP based on ATR.
        """
        atr_val = self.atr[0]

        if self.position.size > 0:  # LONG
            sl = self.data.close[0] - atr_val * self.p.sl_atr
            tp = self.data.close[0] + atr_val * self.p.tp_atr
        else:  # SHORT
            sl = self.data.close[0] + atr_val * self.p.sl_atr
            tp = self.data.close[0] - atr_val * self.p.tp_atr

        self.sell(exectype=bt.Order.Stop, price=sl) if self.position.size > 0 else \
            self.buy(exectype=bt.Order.Stop, price=sl)

        self.sell(exectype=bt.Order.Limit, price=tp) if self.position.size > 0 else \
            self.buy(exectype=bt.Order.Limit, price=tp)
